easy_admin:
    site_name: 'Adopta Un Cubano S.L.'

    design:

        menu:
            - { route: 'homepage' , label: 'Volver al sitio', icon: 'home' }
            - { entity: 'Galeria' , label: 'Galeria', icon: 'photo-video' }
            - { entity: 'UserAttributes' , label: 'Atributos', icon: 'attributes' }
            - { entity: 'User' , label: 'Usuario', icon: 'user' }
            - { entity: 'Conversaciones' , label: 'Conversaciones', icon: 'comments' }
            - { entity: 'Mensajes' , label: 'Mensajes', icon: 'envelope-square' }
    entities:

        Galeria:
            class: App\Entity\Galeria

            list:
                fields:
                    - id
                    - { property: 'foto_perfil', type: 'string' }
                    - { property: 'galeria', type: 'array' }
                    - { property: 'usuario', type: 'text' }

        UserAttributes:
            class: App\Entity\UserAttributes

            list:
                fields:
                    - id
                    - esCubano
                    - nombre
                    - apellido1
                    - { property: 'color_pelo', type: 'string' }
                    - { property: 'usuario', type: 'text' }
        User:
            class: App\Entity\User

            list:
                fields:
                    - id
                    - username
                    - { property: 'roles', type: 'json'}
                    - password
                    - { property: 'galeria', type: 'text'}
                    - { property: 'atributos', type: 'text'}
                    - { property: 'conversacionesEmisor'}
                    - { property: 'conversacionesRemitente'}

        Conversaciones:
            class: App\Entity\Conversaciones

        Mensajes:
            class: App\Entity\Mensajes


